### ISSUE TITLE
kernel panicked on multicore branch

### ISSUE THREAD

**Issue by wyfcyx** [rcore-os/rCore_tutorial#12]
Sometimes kernel panicked when typing commands in the user shell, the following two errors could be found in the panic infomation:
```rust
panicked at 'called `Option::unwrap()` on a `None` value', src/process/processor.rs:100:40
panicked at 'thread not exist!', src/process/thread_pool.rs:49:31
```
Maybe there are some bugs in the scheduling module or the thread management module.

**Comment by wyfcyx** [comment]
The main reason is that the function named `cpuid()` wasn't implemented correctly. To be specific,
```rust
// os/src/interrupt.rs
#[inline(always)]
pub fn cpuid() -> usize {
    let cpuid: usize;
    unsafe {
        //asm!("" : "={x3}"(cpuid)); // before
        asm!("mv $0, gp" : "=r"(cpuid)); // fixed
    }
    cpuid
} 
```
It led to the result that the thread which was assigned to hart1~3 still believe that it was on hart0, and finally panicked in `yield_now`.
Now an user program can run on multi-cores and the kernel won't crash.(Test with rust/switch)
